# Utilise une image Python de base
FROM python:3.11-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de ton projet
COPY . /app

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port sur lequel l'application Flask écoute
EXPOSE 5000

# Commande pour lancer l'application Flask
CMD ["python", "app\app.py"]
